### ISSUE TITLE
The workspace creation has problems or when it is created the lila lichess will not start 

### ISSUE THREAD

**Issue by lowdef** [lichess-org/lila-gitpod#34]
Inspired by the article on lichess:
https://lichess.org/blog/ZUviXRIAACYAVtMm/lichess-development-made-easy-with-gitpod

Version used:
https://gitpod.io/start/#lichessorg-liladocker-cc57v3i3xt3

Browser used:
Firefox 119.0 (64-bit) / Mozilla Firefox Snap for Ubuntu

![image](https://github.com/lichess-org/lila-gitpod/assets/8688088/1994e667-65d8-4114-9468-6c0fa184c76d)

_Case 1 Workspace creation fails completely:_

Error Message: "Error: 13 INTERNAL: cannot resolve image: failed to do request: Head "https://registry-1.docker.io/v2/gitpod/workspace-full/manifests/latest": EOF"

![image](https://github.com/lichess-org/lila-gitpod/assets/8688088/bb3fb1e1-5b5b-47ee-81f2-65f9bd8d9ad1)

_Case 2 lila lichess does not start

![image](https://github.com/lichess-org/lila-gitpod/assets/8688088/f0967b9c-843f-4a48-96b8-d445f176e5d9)

Error message: "✘ lila_docker_rs Error                                                    6.4s 
Error response from daemon: Get "https://registry-1.docker.io/v2/library/rust/manifests/sha256:666012b6779ebb6be2acb771b8627716662cf699502e734652c4799ae4199691": EOF"

**Comment by fitztrev** [comment]
Docker Hub is having some service issues at the moment. https://www.dockerstatus.com/

**Comment by fitztrev** [comment]
Thanks for reporting. Seems to be resolved now. I've been able to start a workspace.

**Comment by lowdef** [comment]
Thanks

**Comment by lowdef** [comment]
works now. really cool!
